In [31]:
import torch
xs = torch.linspace(0, 352 - 1, 22, dtype=torch.float).view(1, 1, 22).expand(41, 8, 22)
ys = torch.linspace(0, 128 - 1, 8, dtype=torch.float).view(1, 8, 1).expand(41, 8, 22)
ds = torch.arange(4.0, 45.0, 1.0, dtype=torch.float).view(-1, 1, 1).expand(-1, 8, 22)
frustum = torch.stack((xs, ys, ds), -1)
frustum[6][7][3]
# print(ys)
# print(ds.shape)


tensor([ 50.1429, 127.0000,  10.0000])

In [45]:
import torch

# 创建一个随机张量，形状为 168648 x 64
x = torch.ones(3, 3)
print(x)
# 基于第 0 维计算累积和
x = torch.cumsum(x, dim=0)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

In [42]:
ranks = torch.randn(5)
print(ranks)
print(ranks[1:])
print(ranks[:-1])
(ranks[1:] != ranks[:-1])

tensor([-1.0675,  0.1165, -2.4155, -0.3312,  0.6427])
tensor([ 0.1165, -2.4155, -0.3312,  0.6427])
tensor([-1.0675,  0.1165, -2.4155, -0.3312])


tensor([True, True, True, True])

In [46]:
x = torch.cat((x[:1], x[1:] - x[:-1]))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])